#!/bin/sh
echo "💅 Run KtLint..."
if ! ./gradlew ktlintCheck; then
  echo "❌ KtLint detected errors. Abort commit."
  exit 1
fi

echo "🔍 Run Detekt..."
./gradlew detekt
if ! ./gradlew detekt; then
  echo "❌ Detekt detected problems. Abort commit."
  exit 1
fi

echo "✅ All checks done. Continue commit."
exit 0
